### ISSUE TITLE
Support for Thrustmaster T500RS

### ISSUE THREAD

**Issue by hoover67** [her001/tmdrv#5]
First of all, thanks for your efforts in getting these wheels to work on Linux. 

I'm trying to use the script to initialize my T500RS (right now I'm trying to get the pedals working correctly) and I have created the following file in tm_devices: 

```
name = 'Thrustmaster T500RS'
idVendor = 0x044f
idProduct = [0xb65d]
control = [
	{'step':1, 'request_type':0x41, 'request':83, 'value':0x0001, 'index':0x0000, 'data':b''},
	{'step':2, 'request_type':0x41, 'request':83, 'value':0x0004, 'index':0x0000, 'data':b''},
]
jscal = '6,1,255,32767,32767,21844,21844,1,3,511,511,1394469,1394469,1,3,511,511,1394469,1394469,1,3,511,511,1394469,1394469,1,0,0,0,536870912,536870912,1,0,0,0,536870912,536870912'
dev_by_id = 'usb-Thrustmaster_Thrustmaster_FFB_Wheel-joystick'

```
It's basically a cut and paste from the thrustmaster_tx file, with the name, idProduct and dev_by_id fields changed to (hopefully) reflect the t500RS on my system (alongside HOTAS Warthog and two MFD frames): 

```
$ lsusb -d 0x044f: 
Bus 002 Device 007: ID 044f:b65d ThrustMaster, Inc. <<<---  this is the same product id as the TX
Bus 002 Device 010: ID 044f:b352 ThrustMaster, Inc. 
Bus 002 Device 009: ID 044f:b351 ThrustMaster, Inc. 
Bus 001 Device 004: ID 044f:0402 ThrustMaster, Inc. 
Bus 001 Device 003: ID 044f:0404 ThrustMaster, Inc. 

```
When I try to initialize the device however I'm getting the following error: 

```
$ python tmdrv.py -d thrustmaster_t500rs
Traceback (most recent call last):
  File "tmdrv.py", line 109, in <module>
    initialize(args.device)
  File "tmdrv.py", line 45, in initialize
    m['data'],
  File "tmdrv.py", line 77, in _control_init
    idVendor, idProduct,
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 2298, in openByVendorIDAndProductID
    return result.open()
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 2067, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

```
I'm pretty new to all of this USB stuff, but have nearly 30 years of Unix / Linux experience so I'm not afraid of the shell... I'd love to help with getting this wheel to work on Linux if I may, but right now I'm a bit stuck 
as to what to do next. 

evtest finds the device fine: 

```
$ evtest /dev/input/event8 
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x44f product 0xb65d version 0x100
Input device name: "Thrustmaster Thrustmaster FFB Wheel"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 306 (BTN_C)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 309 (BTN_Z)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 314 (BTN_SELECT)
    Event code 315 (BTN_START)
    Event code 316 (BTN_MODE)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   2669
      Min        0
      Max     4095
      Fuzz      15
      Flat     255
    Event code 1 (ABS_Y)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 2 (ABS_Z)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 5 (ABS_RZ)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
```

Thanks in advance for any ideas, 

Uwe

**Comment by hoover67** [comment]
lsusb -v output: 
```
 lsusb -v -d 0x044f:0xb65d

Bus 002 Device 007: ID 044f:b65d ThrustMaster, Inc. 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x044f ThrustMaster, Inc.
  idProduct          0xb65d 
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     151
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               2
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               4

```

**Comment by hoover67** [comment]
dmesg output when connecting the wheel to the USB port (directly attached to the motherboard): 
```
USB disconnect, device number 7
[26476.964350] usb 2-1.6: new full-speed USB device number 11 using ehci-pci
[26477.077446] usb 2-1.6: New USB device found, idVendor=044f, idProduct=b65d
[26477.077448] usb 2-1.6: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[26477.077450] usb 2-1.6: Product: Thrustmaster FFB Wheel
[26477.077451] usb 2-1.6: Manufacturer: Thrustmaster
[26477.083848] input: Thrustmaster Thrustmaster FFB Wheel as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/0003:044F:B65D.0008/input/input26
[26477.084020] hid-generic 0003:044F:B65D.0008: input,hidraw4: USB HID v1.00 Gamepad [Thrustmaster Thrustmaster FFB Wheel] on usb-0000:00:1d.0-1.6/input0

```

**Comment by her001** [comment]
Without having a USB capture of the traffic between the Windows driver and the device, tweaking files to try to to initialize your wheel is just guesswork. It is very possible that we could get it working this way, but it would be optimal to use your Windows install.

To answer what you [asked earlier](https://github.com/her001/tmdrv/issues/4#issuecomment-304085075):
> I also still have a win7 install and will take a look at USBPcap to see if I can capture any traffic. I assume I need to set this up first and then plug the wheel into the usb port?

Yes, you will need to have to start the USBPcap capture before plugging the device in, stop it after the wheel is initialized, then share that data with me. You can check out some of the information on their [website](http://desowin.org/usbpcap/tour.html) if you need help with that, but I cannot walk you through a capture on Windows. With this capture data, I should be able to determine if support for your wheel can be added to tmdrv.

**Comment by hoover67** [comment]
I've now installed usbpcap and the latest wireshark version. I followed the steps outlined in the "illustrated tour" on the usbpcap website and create a capture file. 

I started usbpcap with the t500rs connected, then connected it to the USB port, pressed the pedals and some buttons (as per instructions). 

Please let me know if there's anything else I can help with.

Thanks in advance & best wishes, 

Uwe

[t500rs.zip](https://github.com/her001/tmdrv/files/1032323/t500rs.zip)

**Comment by her001** [comment]
Awesome!

Can you try out the following branch and tell me how it goes?

https://github.com/her001/tmdrv/tree/t500rs

I expect it to properly initialize, with correct buttons/axis. The wheel and pedals will probably have large deadzones even if everything else works; we will still need to calibrate it.

If it does work except for the deadzones, I ask that you do one more thing: run `jscal -c` to calibrate the wheel. After this, the deadzones should be set correctly. If they are, please send me the output of `jscal -p` and the name of the device in `/dev/input/by-id/`, the latter of which should like something like `usb-Thrustmaster_Thrustmaster_T500RS-joystick`.

**Comment by hoover67** [comment]
Hi Andrew,

thanks for your quick reply. When running the script as "root", the wheel initializes as it does on windows or when unplugging / replugging the device. I get the following exception: 
```
python tmdrv.py -d thrustmaster_t500rs
Traceback (most recent call last):
  File "tmdrv.py", line 111, in <module>
    initialize(args.device)
  File "tmdrv.py", line 45, in initialize
    m['data'],
  File "tmdrv.py", line 92, in _control_init
    data,
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 1453, in controlWrite
    sizeof(data), timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 1429, in _controlTransfer
    mayRaiseUSBError(result)
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorPipe: LIBUSB_ERROR_PIPE [-9]
```
Running the script as my user results in an error too, but I guess that's a simple udev rule. 

jstest-gtk works like a charm, I don't see any exessive deadzones (they all range from -32676 to +32676 as it seems) 
...
jscal -p /dev/input/js3jscal -s 6,1,0,16439,16439,32879,32879,1,0,511,511,1054724,1052655,1,0,512,512,1052655,1052655,1,0,510,510,1052655,1050595,1,0,0,0,536854528,536854528,1,0,0,0,536854528,536854528 /dev/input/js3

...
by-id device name: 

...

$ ls -l /dev/input/by-id/usb-Thrustmaster_TRS_Racing_wheel-*
lrwxrwxrwx 1 root root 9 Mai 26 19:32 /dev/input/by-id/usb-Thrustmaster_TRS_Racing_wheel-event-joystick -> ../event8
lrwxrwxrwx 1 root root 6 Mai 26 19:32 /dev/input/by-id/usb-Thrustmaster_TRS_Racing_wheel-joystick -> ../js3

...


![bildschirmfoto vom 2017-05-26 19-36-58](https://cloud.githubusercontent.com/assets/16132170/26505877/b67b4ea0-424a-11e7-80ae-214f3e34093b.png)

**Comment by her001** [comment]
Excellent! I'm going to push the jscal config then merge support for the t500rs into master.

As for the exception you are getting, can you open a new issue for that? Just a guess, but that could be caused by using Python 2.

**Comment by hoover67** [comment]
Thanks for the update! Again, there was no need to calibrate the wheel on my system, all axes worked over their entire range without any signifcant deadzones. I calibrated the wheel using jstest-gtk just to be sure, so I hope I posted the correct values.

**Comment by hoover67** [comment]
Am I correct in assuming I only need to run this script exactly once? I just powered down my machine and started it up again, and jstest-gtk seems to have remembered all the axes and their calibration values. 

Trying to run the script as "root" now using either python2.7 or python3 now results in an error: 

```
# python tmdrv.py -d thrustmaster_t500rs
Error getting handle for device 044f:b65d (Thrustmaster T500RS Step 1).
Traceback (most recent call last):
  File "tmdrv.py", line 111, in <module>
    initialize(args.device)
  File "tmdrv.py", line 45, in initialize
    m['data'],
  File "tmdrv.py", line 82, in _control_init
    raise usb1.USBErrorNotFound('Device not found or wrong permissions')
usb1.USBErrorNotFound: Unknown error [Device not found or wrong permissions]
```
Is this a bug or a feature? ;-) 

All the best, Uwe

**Comment by her001** [comment]
You will not need to run it again until the device loses power, which is what resets the state it is in. Since it is no longer in the initial, non-working state, it is expected that the device will not be found.
