### ISSUE TITLE
Support Thrustmaster TMX

### ISSUE THREAD

**Issue by her001** [her001/tmdrv#7]
I suspect that this wheel will initialize in the same way as the Thrustmaster TX, but I'll need someone with the hardware to share with me the capture data.

With the USB traffic between the Windows driver and the TMX (as with [USBPcap](http://desowin.org/usbpcap)), I should be able to add support to tmdrv. In this case, it will need to be tested and I will need the parameters for calibrating the device with jscal.

**Comment by pastaq** [comment]
[pcaps.zip](https://github.com/her001/tmdrv/files/1168210/pcaps.zip)

Output of my lsusb -v
I have also seen this device show up as b67e

Bus 001 Device 003: ID 044f:b65d ThrustMaster, Inc. 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x044f ThrustMaster, Inc.
  idProduct          0xb65d 
  bcdDevice            1.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     151
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               2
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               4

**Comment by pastaq** [comment]
This is the TMX Force Feedback, not the Pro.

**Comment by pastaq** [comment]
I'm having trouble getting Linux Console to make, and the tmdrv.py cannot import usb1 in spite of me having installed python-libusb1.

**Comment by pastaq** [comment]
Initialization tested on my fork. Let me know if there are other tests you need me to do. I didn't adjust the jscal data at all with the new profile. 
https://github.com/her001/tmdrv/pull/8
