### ISSUE TITLE
Support TrustMaster T150 FFB

### ISSUE THREAD

**Issue by tititeco** [her001/tmdrv#9]
Buttons worked for me...  with configuration of the Thrustmaster T500RS. my problem is this FFB. impossible to turn, steering wheel is hard to turn. Is possible to active ffb or deactivate it ?

**Comment by her001** [comment]
Force feedback is expected not to work, as noted in the readme.

For now, my intentions are to eventually work on getting support in the Linux kernel, including eventual force feedback support. I do not expect that tmdrv will ever enable ffb on its own.
